# -*- coding: utf-8 -*-
"""Generate CatalogAbbreviations.g.cs from catalog_abbreviations.json.

Emits a static class holding the canonical abbreviation map as compiled C# data
(no runtime JSON parsing — AOT-clean).

KEYS ARE QUOTE-STRIPPED. The source JSON holds every key with all quote glyphs
already removed (ט"ז is stored as טז), and the lookup side strips the same glyphs
off the typed/indexed token before probing the map — see
CatalogTocTextRules.StripQuoteGlyphs. That is what makes both ט"ז and טז resolve
through one entry, instead of the map having to enumerate every flavour a user
might type (״ / '' / ׳ / curly quotes).

So this generator emits each key VERBATIM: no flavour expansion. A key that still
contains a quote glyph is a bug in the source data and is reported.

Value = jagged array of alternatives; each alternative = string[] of full-word
tokens (AND-matched). >1 alternative => OR-union at query time.
"""
import json, io, re, sys

data = json.load(io.open("catalog_abbreviations.json", encoding="utf-8"))["abbreviations"]

QUOTE_GLYPHS = re.compile(r"[\"'״׳“”‘’]")

# Guard: the lookup strips these glyphs, so a key containing one can never match.
unreachable = [k for k in data if QUOTE_GLYPHS.search(k)]
if unreachable:
    print("ERROR: keys contain quote glyphs and can never be matched", file=sys.stderr)
    for k in unreachable:
        print("  ", repr(k), "-> strip to", repr(QUOTE_GLYPHS.sub("", k)), file=sys.stderr)
    sys.exit(1)

def flavours(key):
    """Keys are pre-stripped; emitted as-is."""
    return [key]

def cs_string(s):
    # C# verbatim-safe: use regular string with escaped backslash/quote; Hebrew stays literal
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

# Build (flavourKey -> alternatives). Detect collisions across different source keys.
entries = {}   # flavourKey -> (sourceKey, alts)
collisions = []
for src_key, alts in data.items():
    for fk in flavours(src_key):
        if fk in entries and entries[fk][1] != alts:
            collisions.append((fk, entries[fk][0], src_key))
        entries[fk] = (src_key, alts)

lines = []
lines.append("// <auto-generated>")
lines.append("//   Generated from Catalog/catalog_abbreviations.json — DO NOT EDIT BY HAND.")
lines.append("//   Regenerate: scripts/gen_catalog_abbreviations (see the .json for the source data).")
lines.append("//   Keys are QUOTE-STRIPPED; the lookup strips quote glyphs before probing.")
lines.append("// </auto-generated>")
lines.append("namespace KitveiHakodeshService.Catalog;")
lines.append("")
lines.append("/// <summary>Compiled catalog-search abbreviation map. Key = a typed abbreviation")
lines.append("/// (one quote flavour per entry); value = alternatives, each an ordered word list")
lines.append("/// that is AND-matched. More than one alternative => OR-union at query time.</summary>")
lines.append("internal static class CatalogAbbreviations")
lines.append("{")
lines.append("    internal static readonly System.Collections.Generic.Dictionary<string, string[][]> Map = new(System.StringComparer.Ordinal)")
lines.append("    {")
for fk in sorted(entries.keys()):
    _src, alts = entries[fk]
    alt_lits = []
    for words in alts:
        alt_lits.append("new[] { " + ", ".join(cs_string(w) for w in words) + " }")
    val = "new[] { " + ", ".join(alt_lits) + " }"
    lines.append(f"        [{cs_string(fk)}] = {val},")
lines.append("    };")
lines.append("}")

io.open("CatalogAbbreviations.g.cs", "w", encoding="utf-8").write("\n".join(lines) + "\n")

print("source keys:", len(data))
print("flavour keys emitted:", len(entries))
if collisions:
    print("COLLISIONS (same flavour key, different meaning):")
    for fk, a, b in collisions:
        print("  ", repr(fk), "from", repr(a), "and", repr(b))
else:
    print("no flavour-key collisions")
