# -*- coding: utf-8 -*-
"""Generate CatalogAbbreviations.g.cs from catalog_abbreviations.json.

Emits a static class holding the canonical abbreviation map as compiled C# data
(no runtime JSON parsing — AOT-clean). Each source key is expanded to its quote
flavours here at generation time:
  - a key containing ASCII '"'  -> that key, plus the ״ (gershayim) and '' variants
  - a key containing ASCII "'"  -> that key, plus the ׳ (geresh) variant
  - a key with neither (plain phrase like "משנה תורה") -> itself only
Value = jagged array of alternatives; each alternative = string[] of full-word
tokens (AND-matched). >1 alternative => OR-union at query time.
"""
import json, io

data = json.load(io.open("catalog_abbreviations.json", encoding="utf-8"))["abbreviations"]

GERSHAYIM = "״"  # ״
GERESH = "׳"     # ׳

def flavours(key):
    out = [key]
    if '"' in key:
        out.append(key.replace('"', GERSHAYIM))
        out.append(key.replace('"', "''"))
    if "'" in key:
        out.append(key.replace("'", GERESH))
    # dedupe, preserve order
    seen = set(); uniq = []
    for k in out:
        if k not in seen:
            seen.add(k); uniq.append(k)
    return uniq

def cs_string(s):
    # C# verbatim-safe: use regular string with escaped backslash/quote; Hebrew stays literal
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

# Build (flavourKey -> alternatives). Detect collisions across different source keys.
entries = {}   # flavourKey -> (sourceKey, alts)
collisions = []
for src_key, alts in data.items():
    for fk in flavours(src_key):
        if fk in entries and entries[fk][1] != alts:
            collisions.append((fk, entries[fk][0], src_key))
        entries[fk] = (src_key, alts)

lines = []
lines.append("// <auto-generated>")
lines.append("//   Generated from Catalog/catalog_abbreviations.json — DO NOT EDIT BY HAND.")
lines.append("//   Regenerate: scripts/gen_catalog_abbreviations (see the .json for the source data).")
lines.append("//   Each source key is pre-expanded to its quote flavours (\\\" / ״ / '' and ' / ׳).")
lines.append("// </auto-generated>")
lines.append("namespace KitveiHakodeshService.Catalog;")
lines.append("")
lines.append("/// <summary>Compiled catalog-search abbreviation map. Key = a typed abbreviation")
lines.append("/// (one quote flavour per entry); value = alternatives, each an ordered word list")
lines.append("/// that is AND-matched. More than one alternative => OR-union at query time.</summary>")
lines.append("internal static class CatalogAbbreviations")
lines.append("{")
lines.append("    internal static readonly System.Collections.Generic.Dictionary<string, string[][]> Map = new(System.StringComparer.Ordinal)")
lines.append("    {")
for fk in sorted(entries.keys()):
    _src, alts = entries[fk]
    alt_lits = []
    for words in alts:
        alt_lits.append("new[] { " + ", ".join(cs_string(w) for w in words) + " }")
    val = "new[] { " + ", ".join(alt_lits) + " }"
    lines.append(f"        [{cs_string(fk)}] = {val},")
lines.append("    };")
lines.append("}")

io.open("CatalogAbbreviations.g.cs", "w", encoding="utf-8").write("\n".join(lines) + "\n")

print("source keys:", len(data))
print("flavour keys emitted:", len(entries))
if collisions:
    print("COLLISIONS (same flavour key, different meaning):")
    for fk, a, b in collisions:
        print("  ", repr(fk), "from", repr(a), "and", repr(b))
else:
    print("no flavour-key collisions")
